from app.prompts.classification_prompt import (
    CLASSIFICATION_SYSTEM_PROMPT,
    CLASSIFICATION_USER_PROMPT,
    CLASSIFICATION_CATEGORIES,
)
from app.prompts.sentiment_prompt import (
    SENTIMENT_SYSTEM_PROMPT,
    SENTIMENT_USER_PROMPT,
    SENTIMENT_LEVELS,
)
from app.prompts.ticket_generation_prompt import (
    TICKET_GENERATION_SYSTEM_PROMPT,
    TICKET_GENERATION_USER_PROMPT,
)

__all__ = [
    "CLASSIFICATION_SYSTEM_PROMPT",
    "CLASSIFICATION_USER_PROMPT",
    "CLASSIFICATION_CATEGORIES",
    "SENTIMENT_SYSTEM_PROMPT",
    "SENTIMENT_USER_PROMPT",
    "SENTIMENT_LEVELS",
    "TICKET_GENERATION_SYSTEM_PROMPT",
    "TICKET_GENERATION_USER_PROMPT",
]
